jobs:
  include:
    - stage: first
      name: The first to run
      install: skip
      script: './first.sh'
    - stage: Second
      name: Run jobs concurrently
      script: './second1.sh'
    - script: './second2.sh'
