dist: trusty
sudo: true
jobs:
  include:
    - stage: first
      name: The first to run
      install: skip
      script:
        - ./first.sh
    - stage: Second
      script: './second1.sh'
    - script: './second2.sh'
