dist: trusty
sudo: true
jobs:
  include:
    - stage: first
      name: The first to run
      install: skip
      script: './first'
    - stage: Second
      script: './second1'
    - script: './second2'
